const goodSRT = `
[Script Info]
; Script generated by Aegisub 2.1.8
; http://www.aegisub.org/
Title: Default Aegisub file
ScriptType: v4.00+
WrapStyle: 0
PlayResX: 640
PlayResY: 480
ScaledBorderAndShadow: yes
Last Style Storage: Default
Video Zoom: 8
Scroll Position: 168
Active Line: 186
Video Zoom Percent: 1
YCbCr Matrix: TV.601
Audio File: ?video
Video File: ..\..\..\Documents\Crunchyroll\sshades\saint_seiya_hades_01.avi
Video Aspect Ratio: 0
Video Position: 5007

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,30,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,20,20,10,1
Style: Narration,Arial,30,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,-1,0,0,100,100,0,0,1,2,2,2,10,10,10,1

Events
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:02:40.18,0:02:43.52,Default,,0000,0000,0000,,Tú eres el Dios del Inframundo, Hades.
Dialogue: 0,0:02:44.35,0:02:46.56,Default,,0000,0000,0000,,¿Qué quieres tratar conmigo?
Dialogue: 0,0:02:47.05,0:02:48.23,Default,,0000,0000,0000,,Atena.{m: terminología de SS Omega, me gusta más Atenea pero me regiré por lo que han hecho ellos en principio}
Dialogue: 0,0:02:51.47,0:02:54.37,Default,,0000,0000,0000,,Vine a darte la bienvenida.
Dialogue: 0,0:03:04.96,0:03:11.84,Default,,0000,0000,0000,,Atena. Fue solo un sueño, ¿verdad?
Dialogue: 0,0:03:13.72,0:03:18.31,Default,,0000,0000,0000,,Parece que ha llegado la hora.
Dialogue: 0,0:03:18.77,0:03:24.77,Default,,0000,0000,0000,,Esperaba que fuese un simple \Nexceso de preocupación.
Dialogue: 0,0:03:27.21,0:03:31.46,Default,,0000,0000,0000,,Después de la guerra \Nsanta de hace 243 años,
Dialogue: 0,0:03:31.83,0:03:39.44,Default,,0000,0000,0000,,el sello de Atena que contenía\N el mal ha perdido su poder.
Dialogue: 0,0:03:40.56,0:03:48.60,Default,,0000,0000,0000,,Las 108 estrellas malignas encabezadas por Hades\Nresurgirán de las tinieblas.
Dialogue: 0,0:03:49.89,0:03:56.01,Default,,0000,0000,0000,,Una nueva guerra santa está por comenzar.
Dialogue: 0,0:04:09.26,0:04:15.21,Default,,0000,0000,0000,,{\an8}El comienzo de una nueva guerra santa
Dialogue: 0,0:04:22.85,0:04:24.80,Default,,0000,0000,0000,,¿Desde cuándo está así?
Dialogue: 0,0:04:25.09,0:04:29.02,Default,,0000,0000,0000,,Estaba bien hace dos horas.
Dialogue: 0,0:04:30.57,0:04:34.13,Default,,0000,0000,0000,,¿Quién profanaría la \Ntumba de un Caballero?{m: terminología de SS Omega}
Dialogue: 0,0:04:34.34,0:04:38.77,Default,,0000,0000,0000,,¿Qué vas a hacer con el \Ncuerpo de un Caballero?
Dialogue: 0,0:04:39.01,0:04:40.19,Default,,0000,0000,0000,,Esperen.
Dialogue: 0,0:04:40.65,0:04:47.05,Default,,0000,0000,0000,,No parece haber sido abierta desde fuera.\NMás bien se ve como si la hubieran forzado desde dentro.
Dialogue: 0,0:04:48.00,0:04:49.12,Default,,0000,0000,0000,,Tienes razón.
Dialogue: 0,0:04:50.64,0:04:54.78,Default,,0000,0000,0000,,¿Entonces estás diciendo que \Nel cuerpo se escapó de la tumba?
Dialogue: 0,0:04:55.46,0:04:58.73,Default,,0000,0000,0000,,Imposible. Un cuerpo no puede hacer eso.
Dialogue: 0,0:04:59.05,0:05:02.38,Default,,0000,0000,0000,,No. Hay uno que sí puede hacerlo.
Dialogue: 0,0:05:08.87,0:05:11.11,Default,,0000,0000,0000,,Es aquel que controla la muerte.
Dialogue: 0,0:05:35.97,0:05:41.22,Default,,0000,0000,0000,,En la distancia ha explotado\N un Cosmo de gran malicia.
Dialogue: 0,0:05:45.59,0:05:46.71,Default,,0000,0000,0000,,No puede ser...
Dialogue: 0,0:05:58.36,0:06:00.57,Default,,0000,0000,0000,,Alto ahí.
Dialogue: 0,0:06:03.24,0:06:07.43,Default,,0000,0000,0000,,Si das un paso más, no podré \Ngarantizar que sigas con vida.
Dialogue: 0,0:06:19.22,0:06:24.90,Default,,0000,0000,0000,,Mu, no hay forma de que me puedas atacar.
Dialogue: 0,0:06:25.00,0:06:25.83,Default,,0000,0000,0000,,¿Qué?
Dialogue: 0,0:06:28.30,0:06:31.91,Default,,0000,0000,0000,,¿Ya olvidaste mi rostro?
Dialogue: 0,0:06:40.99,0:06:47.57,Default,,0000,0000,0000,,Imposible... ¡No puede ser! ¡Tú eres...!
Dialogue: 0,0:06:50.21,0:06:54.89,Default,,0000,0000,0000,,Qué poco respeto. Arrodíllate.
Dialogue: 0,0:06:56.79,0:07:00.89,Default,,0000,0000,0000,,¿Qué ocurre? ¿No escuchaste mis órdenes?
Dialogue: 0,0:07:04.48,0:07:08.06,Default,,0000,0000,0000,,Eso. Así está bien.
Dialogue: 0,0:07:08.73,0:07:12.23,Default,,0000,0000,0000,,No puedes desobedecerme.
Dialogue: 0,0:07:17.02,0:07:20.09,Default,,0000,0000,0000,,Mu, te daré esta orden.
Dialogue: 0,0:07:21.78,0:07:27.99,Default,,0000,0000,0000,,Tráeme la cabeza de Atena\N en las próximas doce horas.
Dialogue: 0,0:07:29.49,0:07:31.53,Default,,0000,0000,0000,,Puedes hacerlo.
Dialogue: 0,0:07:31.78,0:07:32.96,Default,,0000,0000,0000,,Yo...
Dialogue: 0,0:07:33.18,0:07:37.47,Default,,0000,0000,0000,,¿Por qué dudas?\N Deprisa, ve por la cabeza de Atena.
Dialogue: 0,0:07:37.78,0:07:42.40,Default,,0000,0000,0000,,Incluso si me lo ordenas,\N no puedo hacer eso.
Dialogue: 0,0:07:46.88,0:07:51.85,Default,,0000,0000,0000,,Deberías saber lo que \Nconlleva desobedecerle.
Dialogue: 0,0:07:52.79,0:07:53.97,Default,,0000,0000,0000,,¡Esa voz!
Dialogue: 0,0:08:06.20,0:08:07.33,Default,,0000,0000,0000,,Tú eres...
Dialogue: 0,0:08:07.98,0:08:10.05,Default,,0000,0000,0000,,Parece que me recuerdas.
Dialogue: 0,0:08:13.38,0:08:14.57,Default,,0000,0000,0000,,Ustedes dos...
Dialogue: 0,0:08:18.52,0:08:20.28,Default,,0000,0000,0000,,Deathmask de Cáncer.
Dialogue: 0,0:08:21.53,0:08:23.54,Default,,0000,0000,0000,,Afrodita de Piscis.
Dialogue: 0,0:08:24.00,0:08:26.52,Default,,0000,0000,0000,,Ustedes... Esos cuerpos.
Dialogue: 0,0:08:28.08,0:08:32.81,Default,,0000,0000,0000,,Sus espíritus están vagando en el limbo.
Dialogue: 0,0:08:33.27,0:08:37.80,Default,,0000,0000,0000,,No en el limbo. Hemos jurado \Nlealtad a Hades-sama.
Dialogue: 0,0:08:38.07,0:08:40.42,Default,,0000,0000,0000,,Y se nos ha dado nueva vida.
Dialogue: 0,0:08:41.90,0:08:45.30,Default,,0000,0000,0000,,¿Hades? El Señor del Inframundo...
Dialogue: 0,0:08:48.66,0:08:53.48,Default,,0000,0000,0000,,Hacerse esclavos de Hades\N a cambio de su resurrección...
Dialogue: 0,0:08:53.86,0:08:56.28,Default,,0000,0000,0000,,Y venir por la vida de Atena...
Dialogue: 0,0:08:57.82,0:09:02.27,Default,,0000,0000,0000,,¡¿Adónde fue su dignidad \Ncomo Caballeros de Atena?!
Dialogue: 0,0:09:02.69,0:09:03.99,Default,,0000,0000,0000,,¡Cállate!
Dialogue: 0,0:09:04.19,0:09:09.89,Default,,0000,0000,0000,,Estás disfrutando de este mundo,\N ¡¿cómo ibas a entender el horror del Inframundo?!
Dialogue: 0,0:09:19.68,0:09:24.08,Default,,0000,0000,0000,,¿Por qué llevan las Armaduras de Oro? No...
Dialogue: 0,0:09:24.63,0:09:29.05,Default,,0000,0000,0000,,Oscuras como las sombras,\N brillan tan fríamente como la luna.
Dialogue: 0,0:09:29.71,0:09:32.01,Default,,0000,0000,0000,,No son Armaduras de Oro.
Dialogue: 0,0:09:32.58,0:09:35.65,Default,,0000,0000,0000,,Así es, no son Armaduras de Oro.
Dialogue: 0,0:09:36.03,0:09:38.90,Default,,0000,0000,0000,,Son Armaduras del Inframundo, Sobrepellices.{m: "Surplices", he pensado que no había beneficio alguno al dejarlo en inglés, la palabra es poco común de todos modos}
Dialogue: 0,0:09:39.42,0:09:44.55,Default,,0000,0000,0000,,Símbolo de que somos Espectros,\N los guerreros del Inframundo del Hades-sama.
Dialogue: 0,0:09:44.98,0:09:48.57,Default,,0000,0000,0000,,Apártate, Mu. No sirve de \Nnada que sigamos hablando.
Dialogue: 0,0:09:55.38,0:09:57.50,Default,,0000,0000,0000,,¿Pretendes desobedecerle?
Dialogue: 0,0:09:57.90,0:10:03.67,Default,,0000,0000,0000,,Es cierto que no puedo \Noponerme a esta persona.{m: "okata" indica algo como "caballero" o "señor", es un trato respetuoso}
Dialogue: 0,0:10:04.22,0:10:09.24,Default,,0000,0000,0000,,Pero ¿creen que por eso dejaré \Nque consigan lo que les plazca?
Dialogue: 0,0:10:09.62,0:10:11.68,Default,,0000,0000,0000,,Entonces tendremos que usar la fuerza.
Dialogue: 0,0:10:20.38,0:10:22.68,Default,,0000,0000,0000,,¡Sekishiki Meikai Ha!
Dialogue: 0,0:10:28.08,0:10:31.06,Default,,0000,0000,0000,,Repelió el Meikai Ha.
Dialogue: 0,0:10:34.94,0:10:36.54,Default,,0000,0000,0000,,Espera, ¿qué es esto?
Dialogue: 0,0:10:42.44,0:10:45.30,Default,,0000,0000,0000,,Espera, Deathmask.
Dialogue: 0,0:10:46.54,0:10:50.64,Default,,0000,0000,0000,,La técnica de Mu no funcionará \Nante mí, Afrodita.
Dialogue: 0,0:10:54.00,0:10:57.04,Default,,0000,0000,0000,,La rosa negra que devora todo lo que toca.
Dialogue: 0,0:10:57.44,0:10:59.63,Default,,0000,0000,0000,,¡Piranhian Rose!
Dialogue: 0,0:11:21.44,0:11:23.06,Default,,0000,0000,0000,,¿Ahora lo entienden?
Dialogue: 0,0:11:24.09,0:11:28.05,Default,,0000,0000,0000,,Es imposible romper el Crystal Wall.{m: he elegido ponerlo así al ser una técnica, aunque se podría traducir directamente}
Dialogue: 0,0:11:28.65,0:11:36.04,Default,,0000,0000,0000,,Atacar el Crystal Wall es como atacar \Nsu propio reflejo en un espejo.
Dialogue: 0,0:11:38.24,0:11:43.00,Default,,0000,0000,0000,,El impacto se reflejará y \Nse volverá contra ustedes.
Dialogue: 0,0:11:44.98,0:11:48.89,Default,,0000,0000,0000,,¿No has tenido suficiente, Mu?
Dialogue: 0,0:11:49.58,0:11:53.00,Default,,0000,0000,0000,,Estos dos son mis subordinados.
Dialogue: 0,0:11:53.27,0:11:58.79,Default,,0000,0000,0000,,Todo lo que estás haciendo \Nconstituye una rebelión en mi contra.
Dialogue: 0,0:12:01.98,0:12:05.05,Default,,0000,0000,0000,,Quita el Crystal Wall.
Dialogue: 0,0:12:07.49,0:12:10.31,Default,,0000,0000,0000,,Si no lo haces tú, lo haré yo.
Dialogue: 0,0:12:10.71,0:12:15.30,Default,,0000,0000,0000,,Tus técnicas no pueden detenerme.
Dialogue: 0,0:12:34.45,0:12:39.04,Default,,0000,0000,0000,,Ahora, vayan a donde duerme Atena,\N la Cámara del Gran Patriarca.
Dialogue: 0,0:12:39.27,0:12:41.74,Default,,0000,0000,0000,,Y tomen su cabeza.
Dialogue: 0,0:12:42.26,0:12:46.36,Default,,0000,0000,0000,,¡Protegimos el Santuario, así que \Nconocemos el camino de las doce casas!
Dialogue: 0,0:12:46.59,0:12:49.75,Default,,0000,0000,0000,,Es fácil llegar a la Cámara del Patriarca.
Dialogue: 0,0:12:50.68,0:12:56.41,Default,,0000,0000,0000,,Ya basta, Mu. Te dije \Nque son mis subordinados.
Dialogue: 0,0:12:56.87,0:13:02.79,Default,,0000,0000,0000,,Alzar el puño ante ellos es \Nlo mismo que hacerlo ante mí.
Dialogue: 0,0:13:03.16,0:13:06.43,Default,,0000,0000,0000,,¿Alzarías el puño ante mí, Mu?
Dialogue: 0,0:13:12.46,0:13:13.87,Default,,0000,0000,0000,,¡Apártate!
Dialogue: 0,0:13:19.41,0:13:20.51,Default,,0000,0000,0000,,Este maldito...
Dialogue: 0,0:13:21.22,0:13:27.01,Default,,0000,0000,0000,,Proteger la Casa de Aries\N del mal es mi deber.
Dialogue: 0,0:13:27.47,0:13:30.89,Default,,0000,0000,0000,,Aunque signifique mi muerte, \Nno los dejaré pasar.
Dialogue: 0,0:13:38.86,0:13:41.13,Default,,0000,0000,0000,,¡Entonces te mataré!
Dialogue: 0,0:14:15.76,0:14:17.77,Default,,0000,0000,0000,,¡¿Qui-quién se atrevió a interferir?!
Dialogue: 0,0:14:28.36,0:14:29.89,Default,,0000,0000,0000,,Seiya.
Dialogue: 0,0:14:35.91,0:14:37.66,Default,,0000,0000,0000,,Mu, ¿qué ocurre?
Dialogue: 0,0:14:37.98,0:14:41.63,Default,,0000,0000,0000,,¿Por qué te estaban golpeando así?
Dialogue: 0,0:14:42.35,0:14:43.64,Default,,0000,0000,0000,,¿Quiénes son estos tipos?
Dialogue: 0,0:14:44.64,0:14:47.03,Default,,0000,0000,0000,,Afrodita, Deathmask.
Dialogue: 0,0:14:47.25,0:14:51.91,Default,,0000,0000,0000,,Murieron en la batalla \Nde las doce casas. ¿Por qué?
Dialogue: 0,0:14:52.16,0:14:55.67,Default,,0000,0000,0000,,¿Es un sueño? ¿Son fantasmas?
Dialogue: 0,0:14:56.07,0:14:57.85,Default,,0000,0000,0000,,No son fantasmas.
Dialogue: 0,0:14:59.00,0:15:03.92,Default,,0000,0000,0000,,Ahora son guerreros de Hades,\N Señor del Inframundo, Espectros.
Dialogue: 0,0:15:03.92,0:15:07.38,Default,,0000,0000,0000,,¿Espectros? ¿Quién es Hades?
Dialogue: 0,0:15:10.96,0:15:18.60,Default,,0000,0000,0000,,El verdadero enemigo al que Atena \Ndebe derrotar. Ese es Hades.
Dialogue: 0,0:15:20.61,0:15:25.81,Default,,0000,0000,0000,,Entre Hades, que intenta dominar \Nel mundo con oscuridad y temor,
Dialogue: 0,0:15:26.14,0:15:31.98,Default,,0000,0000,0000,,y Atena, que intenta detenerlo, ha \Nhabido una larga y dura batalla.
Dialogue: 0,0:15:32.59,0:15:37.89,Default,,0000,0000,0000,,Ahora, el sello de Atena se ha roto,
Dialogue: 0,0:15:38.18,0:15:43.04,Default,,0000,0000,0000,,y Hades quiere volver a enfrentarse a Atena.
Dialogue: 0,0:15:43.78,0:15:55.84,Default,,0000,0000,0000,,Para dar freno a sus ambiciones,\NAtena y los Caballeros han resucitado en esta era.
Dialogue: 0,0:15:56.10,0:16:01.21,Default,,0000,0000,0000,,Ya veo. Así que las batallas \Nhasta ahora eran simple práctica.
Dialogue: 0,0:16:01.73,0:16:03.64,Default,,0000,0000,0000,,Si lo entiendes, vete.
Dialogue: 0,0:16:05.00,0:16:10.88,Default,,0000,0000,0000,,Este no es lugar para un \NCaballero de Bronce como tú.
Dialogue: 0,0:16:11.31,0:16:12.98,Default,,0000,0000,0000,,Date prisa y vete.
Dialogue: 0,0:16:13.18,0:16:17.94,Default,,0000,0000,0000,,¿Qué estás diciendo? \NNo puedo irme, yo también lucharé.
Dialogue: 0,0:16:18.58,0:16:19.96,Default,,0000,0000,0000,,Por Atena.
Dialogue: 0,0:16:20.33,0:16:25.44,Default,,0000,0000,0000,,Si desobedeces, te espera la \Nmuerte. Es una orden de Atena.
Dialogue: 0,0:16:25.64,0:16:30.92,Default,,0000,0000,0000,,¿Qué? ¿Atena, Saori-san, \Npretende quitarnos de en medio
Dialogue: 0,0:16:31.24,0:16:33.40,Default,,0000,0000,0000,,y dio órdenes de matarnos si desobedecíamos?
Dialogue: 0,0:16:34.62,0:16:38.93,Default,,0000,0000,0000,,Sí, así lo desea Atena.
Dialogue: 0,0:16:39.30,0:16:43.70,Default,,0000,0000,0000,,Eso es mentira. Somos \Nlos Caballeros de Atena.
Dialogue: 0,0:16:52.51,0:16:53.29,Default,,0000,0000,0000,,Mu.
Dialogue: 0,0:16:53.83,0:16:58.14,Default,,0000,0000,0000,,Debe haber algún error.\N Déjame ver a Saori-san, Atena.
Dialogue: 0,0:17:00.13,0:17:02.01,Default,,0000,0000,0000,,Hay algún error.
Dialogue: 0,0:17:09.71,0:17:11.68,Default,,0000,0000,0000,,No es un error.
Dialogue: 0,0:17:12.12,0:17:15.58,Default,,0000,0000,0000,,Es un error. ¡No puedo creerlo!
Dialogue: 0,0:17:16.71,0:17:18.40,Default,,0000,0000,0000,,¡Qué molesto eres!
Dialogue: 0,0:17:20.79,0:17:25.62,Default,,0000,0000,0000,,No era suficiente con interferir, sino \Nque ahora también te quejas. Ya basta.
Dialogue: 0,0:17:28.06,0:17:31.01,Default,,0000,0000,0000,,¡Ya no eres necesario!
Dialogue: 0,0:17:38.90,0:17:44.88,Default,,0000,0000,0000,,¡No es posible que Saori-san dijera eso!
Dialogue: 0,0:17:47.14,0:17:48.35,Default,,0000,0000,0000,,¡Lo haré!
Dialogue: 0,0:18:04.05,0:18:06.81,Default,,0000,0000,0000,,¡Lo haré! ¡Vamos, Deathmask!
Dialogue: 0,0:18:07.44,0:18:12.80,Default,,0000,0000,0000,,¿Qué es esa Armadura tan desaliñada? \NDeberías hacer que Mu te la repare.
Dialogue: 0,0:18:13.10,0:18:17.77,Default,,0000,0000,0000,,¿Crees que puedes derrotarme \Ncon esa Armadura hecha añicos?
Dialogue: 0,0:18:17.96,0:18:20.90,Default,,0000,0000,0000,,Mi Armadura no importa\N a la hora de derrotarte.
Dialogue: 0,0:18:26.99,0:18:28.45,Default,,0000,0000,0000,,¿De verdad?
Dialogue: 0,0:18:32.96,0:18:36.15,Default,,0000,0000,0000,,¡Pegasus Ryuusei Ken!
Dialogue: 0,0:18:43.00,0:18:47.67,Default,,0000,0000,0000,,¡Levántate, Deathmask! ¡Te haré hacer \Nburbujas como un verdadero cangrejo!{m: la gracia de esta frase es que el símbolo de Cáncer es un cangrejo, pero no hay forma fácil de ilustrarlo}
Dialogue: 0,0:18:49.09,0:18:55.38,Default,,0000,0000,0000,,Maldito mocoso, te lanzaré por\N el agujero que lleva al infierno.
Dialogue: 0,0:18:55.67,0:18:59.08,Default,,0000,0000,0000,,Eres tú quien volverá allí por el agujero.
Dialogue: 0,0:18:59.43,0:19:03.05,Default,,0000,0000,0000,,¡Toma esto! ¡Sekishiki Meikai Ha!
Dialogue: 0,0:19:03.94,0:19:05.89,Default,,0000,0000,0000,,¡Pegasus Ryuusei Ken!
Dialogue: 0,0:19:10.54,0:19:11.66,Default,,0000,0000,0000,,¿Qué?
Dialogue: 0,0:19:12.81,0:19:14.44,Default,,0000,0000,0000,,¿Por qué?
Dialogue: 0,0:19:14.73,0:19:20.87,Default,,0000,0000,0000,,Te lo advertí. Si desobedeces, \Nte espera la muerte.
Dialogue: 0,0:19:25.00,0:19:26.53,Default,,0000,0000,0000,,No puede ser.
Dialogue: 0,0:19:30.00,0:19:31.73,Default,,0000,0000,0000,,Saori-san.
Dialogue: 0,0:19:36.32,0:19:40.80,Default,,0000,0000,0000,,¿Es cierto que no nos necesitas más?
Dialogue: 0,0:19:53.97,0:19:58.41,Default,,0000,0000,0000,,¿Por qué? ¿Por qué es eso?
Dialogue: 0,0:20:06.18,0:20:10.42,Default,,0000,0000,0000,,Es cierto. Y te diré algo más.
Dialogue: 0,0:20:10.74,0:20:13.21,Default,,0000,0000,0000,,Mu no tomará solo la vida \Nde los Caballeros de Bronce.
Dialogue: 0,0:20:13.70,0:20:18.06,Default,,0000,0000,0000,,También ofrecerá la vida \Nde Atena a Hades. ¿Lo entiendes?
Dialogue: 0,0:20:20.70,0:20:24.04,Default,,0000,0000,0000,,No me creo eso que dices.
Dialogue: 0,0:20:24.29,0:20:27.97,Default,,0000,0000,0000,,Creerlo o no es problema tuyo.
Dialogue: 0,0:20:28.22,0:20:31.12,Default,,0000,0000,0000,,Pero Mu debe obedecer órdenes sí o sí.
Dialogue: 0,0:20:31.98,0:20:36.95,Default,,0000,0000,0000,,Mientras esa persona esté de nuestro lado...
Dialogue: 0,0:20:37.77,0:20:39.68,Default,,0000,0000,0000,,¿"Esa persona"?
Dialogue: 0,0:20:40.11,0:20:44.07,Default,,0000,0000,0000,,No hay nadie que pueda\N oponerse a esta persona
Dialogue: 0,0:20:44.66,0:20:46.97,Default,,0000,0000,0000,,en este Santuario.
Dialogue: 0,0:20:49.96,0:20:55.90,Default,,0000,0000,0000,,Te lo diré como regalo de despedida.\NEscucha atentamente, Seiya. Su nombre es...
Dialogue: 0,0:21:00.94,0:21:03.91,Default,,0000,0000,0000,,No hagas nada innecesario, Deathmask.
Dialogue: 0,0:21:04.51,0:21:07.11,Default,,0000,0000,0000,,Yo mismo acabaré con Seiya.
Dialogue: 0,0:21:14.50,0:21:15.72,Default,,0000,0000,0000,,Mu.
Dialogue: 0,0:21:16.60,0:21:21.66,Default,,0000,0000,0000,,Seiya, descansa en paz, ¿de acuerdo?
Dialogue: 0,0:21:25.58,0:21:27.60,Default,,0000,0000,0000,,Es mentira, Mu.
Dialogue: 0,0:21:34.17,0:21:37.01,Default,,0000,0000,0000,,¡Starlight Extinction!
Dialogue: 0,0:21:46.94,0:21:49.98,Default,,0000,0000,0000,,¡Saori-san!
Dialogue: 0,0:21:52.61,0:21:54.09,Default,,0000,0000,0000,,Seiya.
Dialogue: 0,0:21:58.08,0:22:02.04,Default,,0000,0000,0000,,Creí haber oído la voz de Seiya.
Dialogue: 0,0:22:06.46,0:22:12.21,Default,,0000,0000,0000,,Bueno, ordené a Seiya y a los \Ndemás no acercarse al Santuario.
Dialogue: 0,0:22:13.21,0:22:15.08,Default,,0000,0000,0000,,No deberían estar por aquí.
Dialogue: 0,0:23:02.22,0:23:08.47,Default,,0000,0000,0000,,Cuando la furia silenciosa de Aries alcanza su cúspide, \NMu ve a los más poderosos Caballeros de Oro convertidos al mal.
Dialogue: 0,0:23:08.70,0:23:14.85,Default,,0000,0000,0000,,Saga, Camus, Shura. ¡¿Ustedes también se volvieron\Nsoldados de Hades y vinieron a matar a Atena?!
Dialogue: 0,0:23:15.25,0:23:20.82,Default,,0000,0000,0000,,Los lamentos de aquellos que fueron guerreros del \Namor y la justicia en la Tierra resuenan en el Santuario.
Dialogue: 0,0:23:21.31,0:23:23.83,Default,,0000,0000,0000,,Saint Seiya: El lamento de los tres
Dialogue: 0,0:23:24.18,0:23:26.72,Default,,0000,0000,0000,,¿Sientes tu Cosmo?

`;

module.exports = goodSRT;
